### ISSUE TITLE
Missing file: test/NoeditFile.sh

### ISSUE THREAD

**Issue by lukehorvat** [noedit/file#1]
Error when running `npm test`:

`sh: ./test/NoeditFile.sh: No such file or directory`

**Comment by greduan** [comment]
Ah thanks. I renamed the file to `NoeditFile.editLines.sh`. Fixing.

Done: https://github.com/noedit/file/commit/636fbd457f1bdb9adf5eed15b195649841767219

Although FYI, at the moment the tests for `NoeditFile` aren't setup right, only the tests for `findLines` work.
